DROP TABLE IF EXISTS "Token";

DROP TABLE IF EXISTS "Tap";

DROP TABLE IF EXISTS "Block";

DROP TABLE IF EXISTS "Bookmarks";

DROP TABLE IF EXISTS "Comments";

DROP TABLE IF EXISTS "Posts";

DROP TABLE IF EXISTS "AdminUser";

DROP TABLE IF EXISTS "SearchRecord";

DROP TABLE IF EXISTS "User";