DROP TABLE IF EXISTS "UserComment";

DROP TABLE IF EXISTS "Comment";

DROP TABLE IF EXISTS "Block";

DROP TABLE IF EXISTS "SavePost";

DROP TABLE IF EXISTS "Tap";

DROP TABLE IF EXISTS "Token";

DROP TABLE IF EXISTS "Posts";

DROP TABLE IF EXISTS "SearchRecord";

DROP TABLE IF EXISTS "User";