// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: adminuser.sql

package db

import (
	"context"
)

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO ADMINUSER (
    EMAIL,
    HASHPASSWORD,
    STAFF_NAME,
    DEPARTMENT
) VALUES(
    $1,
    $2,
    $3,
    $4
) RETURNING email, hashpassword, staff_name, department, joined_at
`

type CreateAdminUserParams struct {
	Email        string `json:"email"`
	Hashpassword string `json:"hashpassword"`
	StaffName    string `json:"staff_name"`
	Department   string `json:"department"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (Adminuser, error) {
	row := q.db.QueryRow(ctx, createAdminUser,
		arg.Email,
		arg.Hashpassword,
		arg.StaffName,
		arg.Department,
	)
	var i Adminuser
	err := row.Scan(
		&i.Email,
		&i.Hashpassword,
		&i.StaffName,
		&i.Department,
		&i.JoinedAt,
	)
	return i, err
}

const deleteAdminUser = `-- name: DeleteAdminUser :exec
DELETE FROM ADMINUSER
WHERE
    EMAIL = $1
`

func (q *Queries) DeleteAdminUser(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteAdminUser, email)
	return err
}

const getPasswordToAdminLogin = `-- name: GetPasswordToAdminLogin :one
SELECT
    HASHPASSWORD
FROM
    ADMINUSER
WHERE
    EMAIL = $1 LIMIT 1
`

func (q *Queries) GetPasswordToAdminLogin(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRow(ctx, getPasswordToAdminLogin, email)
	var hashpassword string
	err := row.Scan(&hashpassword)
	return hashpassword, err
}
