// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: posts.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO POSTS (
    POST_ID,
    USER_ID,
    SHOW_ID,
    TITLE,
    FEEL,
    CONTENT,
    IS_SENSITIVE,
    STATUS
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
) RETURNING user_id, post_id, show_id, title, feel, content, is_sensitive, status, created_at, updated_at
`

type CreatePostParams struct {
	PostID      uuid.UUID `json:"post_id"`
	UserID      uuid.UUID `json:"user_id"`
	ShowID      string    `json:"show_id"`
	Title       string    `json:"title"`
	Feel        string    `json:"feel"`
	Content     []byte    `json:"content"`
	IsSensitive bool      `json:"is_sensitive"`
	Status      string    `json:"status"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.PostID,
		arg.UserID,
		arg.ShowID,
		arg.Title,
		arg.Feel,
		arg.Content,
		arg.IsSensitive,
		arg.Status,
	)
	var i Post
	err := row.Scan(
		&i.UserID,
		&i.PostID,
		&i.ShowID,
		&i.Title,
		&i.Feel,
		&i.Content,
		&i.IsSensitive,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM POSTS
WHERE
    USER_ID = $1
    AND POST_ID = $2 RETURNING user_id, post_id, show_id, title, feel, content, is_sensitive, status, created_at, updated_at
`

type DeletePostParams struct {
	UserID uuid.UUID `json:"user_id"`
	PostID uuid.UUID `json:"post_id"`
}

func (q *Queries) DeletePost(ctx context.Context, arg DeletePostParams) error {
	_, err := q.db.Exec(ctx, deletePost, arg.UserID, arg.PostID)
	return err
}

const getOnePost = `-- name: GetOnePost :one
SELECT
    user_id, post_id, show_id, title, feel, content, is_sensitive, status, created_at, updated_at
FROM
    POSTS
WHERE
    POST_ID = $1
`

func (q *Queries) GetOnePost(ctx context.Context, postID uuid.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getOnePost, postID)
	var i Post
	err := row.Scan(
		&i.UserID,
		&i.PostID,
		&i.ShowID,
		&i.Title,
		&i.Feel,
		&i.Content,
		&i.IsSensitive,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostsList = `-- name: GetPostsList :many
SELECT
    user_id, post_id, show_id, title, feel, content, is_sensitive, status, created_at, updated_at
FROM
    POSTS
ORDER BY
    CREATED_AT DESC
`

func (q *Queries) GetPostsList(ctx context.Context) ([]Post, error) {
	rows, err := q.db.Query(ctx, getPostsList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.UserID,
			&i.PostID,
			&i.ShowID,
			&i.Title,
			&i.Feel,
			&i.Content,
			&i.IsSensitive,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAllPosts = `-- name: GetUserAllPosts :many
SELECT
    user_id, post_id, show_id, title, feel, content, is_sensitive, status, created_at, updated_at
FROM
    POSTS
WHERE
    USER_ID = $1
`

func (q *Queries) GetUserAllPosts(ctx context.Context, userID uuid.UUID) ([]Post, error) {
	rows, err := q.db.Query(ctx, getUserAllPosts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.UserID,
			&i.PostID,
			&i.ShowID,
			&i.Title,
			&i.Feel,
			&i.Content,
			&i.IsSensitive,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPost = `-- name: SearchPost :many
SELECT
    user_id, post_id, show_id, title, feel, content, is_sensitive, status, created_at, updated_at
FROM
    POSTS
WHERE
    TITLE LIKE '%'
               || CAST($1 AS TEXT)
               || '%'
    OR EXISTS (
        SELECT
            1
        FROM
            JSONB_ARRAY_ELEMENTS(CONTENT) AS ELEM,
            JSONB_ARRAY_ELEMENTS(ELEM->'children') AS CHILD
        WHERE
            CHILD->>'text' LIKE '%'
                                || CAST($1 AS TEXT)
                                || '%'
    )
`

func (q *Queries) SearchPost(ctx context.Context, dollar_1 string) ([]Post, error) {
	rows, err := q.db.Query(ctx, searchPost, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.UserID,
			&i.PostID,
			&i.ShowID,
			&i.Title,
			&i.Feel,
			&i.Content,
			&i.IsSensitive,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePosts = `-- name: UpdatePosts :one
UPDATE POSTS
SET
    SHOW_ID = COALESCE($3, SHOW_ID),
    TITLE = COALESCE($4, TITLE),
    FEEL = COALESCE($5, FEEL),
    CONTENT = COALESCE($6, CONTENT),
    IS_SENSITIVE = COALESCE($7, IS_SENSITIVE),
    status = COALESCE($8, status),
    UPDATED_AT = NOW()
WHERE
    USER_ID = $1
    AND POST_ID = $2
RETURNING user_id, post_id, show_id, title, feel, content, is_sensitive, status, created_at, updated_at
`

type UpdatePostsParams struct {
	UserID      uuid.UUID `json:"user_id"`
	PostID      uuid.UUID `json:"post_id"`
	ShowID      string    `json:"show_id"`
	Title       string    `json:"title"`
	Feel        string    `json:"feel"`
	Content     []byte    `json:"content"`
	IsSensitive bool      `json:"is_sensitive"`
	Status      string    `json:"status"`
}

func (q *Queries) UpdatePosts(ctx context.Context, arg UpdatePostsParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePosts,
		arg.UserID,
		arg.PostID,
		arg.ShowID,
		arg.Title,
		arg.Feel,
		arg.Content,
		arg.IsSensitive,
		arg.Status,
	)
	var i Post
	err := row.Scan(
		&i.UserID,
		&i.PostID,
		&i.ShowID,
		&i.Title,
		&i.Feel,
		&i.Content,
		&i.IsSensitive,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
