// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: posts_reaction.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPostsReaction = `-- name: CreatePostsReaction :one
INSERT INTO POSTS_REACTION (
    USER_ID,
    POST_ID,
    P_REACTION_THANKS,
    P_REACTION_HELPFUL,
    P_REACTION_USEFUL,
    P_REACTION_HEART
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
) RETURNING user_id, post_id, p_reaction_thanks, p_reaction_heart, p_reaction_helpful, p_reaction_useful, created_at
`

type CreatePostsReactionParams struct {
	UserID           uuid.UUID `json:"user_id"`
	PostID           uuid.UUID `json:"post_id"`
	PReactionThanks  bool      `json:"p_reaction_thanks"`
	PReactionHelpful bool      `json:"p_reaction_helpful"`
	PReactionUseful  bool      `json:"p_reaction_useful"`
	PReactionHeart   bool      `json:"p_reaction_heart"`
}

func (q *Queries) CreatePostsReaction(ctx context.Context, arg CreatePostsReactionParams) (PostsReaction, error) {
	row := q.db.QueryRow(ctx, createPostsReaction,
		arg.UserID,
		arg.PostID,
		arg.PReactionThanks,
		arg.PReactionHelpful,
		arg.PReactionUseful,
		arg.PReactionHeart,
	)
	var i PostsReaction
	err := row.Scan(
		&i.UserID,
		&i.PostID,
		&i.PReactionThanks,
		&i.PReactionHeart,
		&i.PReactionHelpful,
		&i.PReactionUseful,
		&i.CreatedAt,
	)
	return i, err
}

const deletePostsReaction = `-- name: DeletePostsReaction :exec
DELETE FROM POSTS_REACTION
WHERE 
    USER_ID = $1 AND POST_ID = $2
    AND NOT (P_REACTION_THANKS OR P_REACTION_HEART OR P_REACTION_HELPFUL OR P_REACTION_USEFUL)
`

type DeletePostsReactionParams struct {
	UserID uuid.UUID `json:"user_id"`
	PostID uuid.UUID `json:"post_id"`
}

func (q *Queries) DeletePostsReaction(ctx context.Context, arg DeletePostsReactionParams) error {
	_, err := q.db.Exec(ctx, deletePostsReaction, arg.UserID, arg.PostID)
	return err
}

const getAllPostsReactionData = `-- name: GetAllPostsReactionData :many
SELECT user_id, post_id, p_reaction_thanks, p_reaction_heart, p_reaction_helpful, p_reaction_useful, created_at FROM POSTS_REACTION
`

func (q *Queries) GetAllPostsReactionData(ctx context.Context) ([]PostsReaction, error) {
	rows, err := q.db.Query(ctx, getAllPostsReactionData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostsReaction{}
	for rows.Next() {
		var i PostsReaction
		if err := rows.Scan(
			&i.UserID,
			&i.PostID,
			&i.PReactionThanks,
			&i.PReactionHeart,
			&i.PReactionHelpful,
			&i.PReactionUseful,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsHeartOfTrue = `-- name: GetPostsHeartOfTrue :one
SELECT COUNT(*)
FROM POSTS_REACTION
WHERE P_REACTION_HEART = TRUE AND POST_ID = $1
`

func (q *Queries) GetPostsHeartOfTrue(ctx context.Context, postID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getPostsHeartOfTrue, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPostsHelpfulOfTrue = `-- name: GetPostsHelpfulOfTrue :one
SELECT COUNT(*)
FROM POSTS_REACTION
WHERE P_REACTION_HELPFUL = TRUE AND POST_ID = $1
`

func (q *Queries) GetPostsHelpfulOfTrue(ctx context.Context, postID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getPostsHelpfulOfTrue, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPostsReaction = `-- name: GetPostsReaction :many
SELECT user_id, post_id, p_reaction_thanks, p_reaction_heart, p_reaction_helpful, p_reaction_useful, created_at FROM POSTS_REACTION 
WHERE POST_ID = $1
`

func (q *Queries) GetPostsReaction(ctx context.Context, postID uuid.UUID) ([]PostsReaction, error) {
	rows, err := q.db.Query(ctx, getPostsReaction, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostsReaction{}
	for rows.Next() {
		var i PostsReaction
		if err := rows.Scan(
			&i.UserID,
			&i.PostID,
			&i.PReactionThanks,
			&i.PReactionHeart,
			&i.PReactionHelpful,
			&i.PReactionUseful,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsThanksOfTrue = `-- name: GetPostsThanksOfTrue :one
SELECT COUNT(*)
FROM POSTS_REACTION
WHERE P_REACTION_THANKS = TRUE AND POST_ID = $1
`

func (q *Queries) GetPostsThanksOfTrue(ctx context.Context, postID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getPostsThanksOfTrue, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPostsUsefulOfTrue = `-- name: GetPostsUsefulOfTrue :one
SELECT COUNT(*)
FROM POSTS_REACTION
WHERE P_REACTION_USEFUL = TRUE AND POST_ID = $1
`

func (q *Queries) GetPostsUsefulOfTrue(ctx context.Context, postID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getPostsUsefulOfTrue, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updatePostsReactionHeart = `-- name: UpdatePostsReactionHeart :one
UPDATE POSTS_REACTION
SET 
    P_REACTION_HEART = NOT P_REACTION_HEART
WHERE 
    USER_ID = $1 AND POST_ID = $2
RETURNING user_id, post_id, p_reaction_thanks, p_reaction_heart, p_reaction_helpful, p_reaction_useful, created_at
`

type UpdatePostsReactionHeartParams struct {
	UserID uuid.UUID `json:"user_id"`
	PostID uuid.UUID `json:"post_id"`
}

func (q *Queries) UpdatePostsReactionHeart(ctx context.Context, arg UpdatePostsReactionHeartParams) (PostsReaction, error) {
	row := q.db.QueryRow(ctx, updatePostsReactionHeart, arg.UserID, arg.PostID)
	var i PostsReaction
	err := row.Scan(
		&i.UserID,
		&i.PostID,
		&i.PReactionThanks,
		&i.PReactionHeart,
		&i.PReactionHelpful,
		&i.PReactionUseful,
		&i.CreatedAt,
	)
	return i, err
}

const updatePostsReactionHelpful = `-- name: UpdatePostsReactionHelpful :one
UPDATE POSTS_REACTION
SET 
    P_REACTION_HELPFUL = NOT P_REACTION_HELPFUL
WHERE 
    USER_ID = $1 AND POST_ID = $2
RETURNING user_id, post_id, p_reaction_thanks, p_reaction_heart, p_reaction_helpful, p_reaction_useful, created_at
`

type UpdatePostsReactionHelpfulParams struct {
	UserID uuid.UUID `json:"user_id"`
	PostID uuid.UUID `json:"post_id"`
}

func (q *Queries) UpdatePostsReactionHelpful(ctx context.Context, arg UpdatePostsReactionHelpfulParams) (PostsReaction, error) {
	row := q.db.QueryRow(ctx, updatePostsReactionHelpful, arg.UserID, arg.PostID)
	var i PostsReaction
	err := row.Scan(
		&i.UserID,
		&i.PostID,
		&i.PReactionThanks,
		&i.PReactionHeart,
		&i.PReactionHelpful,
		&i.PReactionUseful,
		&i.CreatedAt,
	)
	return i, err
}

const updatePostsReactionThanks = `-- name: UpdatePostsReactionThanks :one
UPDATE POSTS_REACTION
SET 
    P_REACTION_THANKS = NOT P_REACTION_THANKS
WHERE 
    USER_ID = $1 AND POST_ID = $2
RETURNING user_id, post_id, p_reaction_thanks, p_reaction_heart, p_reaction_helpful, p_reaction_useful, created_at
`

type UpdatePostsReactionThanksParams struct {
	UserID uuid.UUID `json:"user_id"`
	PostID uuid.UUID `json:"post_id"`
}

func (q *Queries) UpdatePostsReactionThanks(ctx context.Context, arg UpdatePostsReactionThanksParams) (PostsReaction, error) {
	row := q.db.QueryRow(ctx, updatePostsReactionThanks, arg.UserID, arg.PostID)
	var i PostsReaction
	err := row.Scan(
		&i.UserID,
		&i.PostID,
		&i.PReactionThanks,
		&i.PReactionHeart,
		&i.PReactionHelpful,
		&i.PReactionUseful,
		&i.CreatedAt,
	)
	return i, err
}

const updatePostsReactionUseful = `-- name: UpdatePostsReactionUseful :one
UPDATE POSTS_REACTION
SET 
    P_REACTION_USEFUL = NOT P_REACTION_USEFUL
WHERE 
    USER_ID = $1 AND POST_ID = $2
RETURNING user_id, post_id, p_reaction_thanks, p_reaction_heart, p_reaction_helpful, p_reaction_useful, created_at
`

type UpdatePostsReactionUsefulParams struct {
	UserID uuid.UUID `json:"user_id"`
	PostID uuid.UUID `json:"post_id"`
}

func (q *Queries) UpdatePostsReactionUseful(ctx context.Context, arg UpdatePostsReactionUsefulParams) (PostsReaction, error) {
	row := q.db.QueryRow(ctx, updatePostsReactionUseful, arg.UserID, arg.PostID)
	var i PostsReaction
	err := row.Scan(
		&i.UserID,
		&i.PostID,
		&i.PReactionThanks,
		&i.PReactionHeart,
		&i.PReactionHelpful,
		&i.PReactionUseful,
		&i.CreatedAt,
	)
	return i, err
}
