-- name: CreatePostsReaction :one
INSERT INTO POSTS_REACTION (
    USER_ID,
    POST_ID,
    P_REACTION_THANKS,
    P_REACTION_HELPFUL,
    P_REACTION_USEFUL,
    P_REACTION_HEART
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
) RETURNING *;

-- name: GetPostsReaction :many
SELECT * FROM POSTS_REACTION 
WHERE POST_ID = $1;

-- name: GetAllPostsReaction :many
SELECT * FROM POSTS_REACTION;

-- name: UpdatePostsReactionThanks :one
UPDATE POSTS_REACTION
SET 
    P_REACTION_THANKS = NOT P_REACTION_THANKS
WHERE 
    USER_ID = $1 AND POST_ID = $2
RETURNING *;

-- name: UpdatePostsReactionHelpful :one
UPDATE POSTS_REACTION
SET 
    P_REACTION_HELPFUL = NOT P_REACTION_HELPFUL
WHERE 
    USER_ID = $1 AND POST_ID = $2
RETURNING *;

-- name: UpdatePostsReactionUseful :one
UPDATE POSTS_REACTION
SET 
    P_REACTION_USEFUL = NOT P_REACTION_USEFUL
WHERE 
    USER_ID = $1 AND POST_ID = $2
RETURNING *;

-- name: UpdatePostsReactionHeart :one
UPDATE POSTS_REACTION
SET 
    P_REACTION_HEART = NOT P_REACTION_HEART
WHERE 
    USER_ID = $1 AND POST_ID = $2
RETURNING *;

-- name: DeletePostsReaction :exec
DELETE FROM POSTS_REACTION
WHERE 
    USER_ID = $1 AND POST_ID = $2
    AND NOT (P_REACTION_THANKS OR P_REACTION_HEART OR P_REACTION_HELPFUL OR P_REACTION_USEFUL);

-- name: GetPostsHeartOfTrue :one
SELECT COUNT(*)
FROM POSTS_REACTION
WHERE P_REACTION_HEART = TRUE AND POST_ID = $1;

-- name: GetPostsThanksOfTrue :one
SELECT COUNT(*)
FROM POSTS_REACTION
WHERE P_REACTION_THANKS = TRUE AND POST_ID = $1;

-- name: GetPostsHelpfulOfTrue :one
SELECT COUNT(*)
FROM POSTS_REACTION
WHERE P_REACTION_HELPFUL = TRUE AND POST_ID = $1;

-- name: GetPostsUsefulOfTrue :one
SELECT COUNT(*)
FROM POSTS_REACTION
WHERE P_REACTION_USEFUL = TRUE AND POST_ID = $1;

